name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
            sudo apt-get update
            sudo apt-get install -y cmake build-essential libsdl2-dev libgl1-mesa-dev
      - name: Configure and Build
        run : |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run Tests
        run : |
          cd build
          ctest --output-on-failure
          

      
