name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libsdl2-dev \
            libgl1-mesa-dev \
            lcov

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_COVERAGE=ON
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage report
        if: ${{ success() }}
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/googletest/*' -o coverage.info
          genhtml coverage.info --output-directory coverage_html

      - name: Upload coverage artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: build/coverage_html

      - name: cppcheck-action
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          std: c++20
          output_file: cppcheck_report.txt